name: Preview

on:
  # Run on all pull requests that update the paper. This should list our
  # paper directory if we have one, or all paper files if they are in
  # our project root folder.
  pull_request:
    paths:
      - 'paper/**'
  # Run every time a paper change is pushed.
  push:
    paths-ignore:
      - 'paper/**'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create draft artifacts
        uses: 'docker://openjournals/inara:latest'
        with:
          args: >-
            -o pdf,docx paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: preview
          path: |
            paper/paper.pdf
            paper/paper.docx
